@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Apr 05 22:51:21 +0300 2021
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim multi_port_adder_behav -key {Behavioral:sim_1:Functional:multi_port_adder} -tclbatch multi_port_adder.tcl -protoinst "protoinst_files/system_top_level.protoinst" -log simulate.log"
call xsim  multi_port_adder_behav -key {Behavioral:sim_1:Functional:multi_port_adder} -tclbatch multi_port_adder.tcl -protoinst "protoinst_files/system_top_level.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
