# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/logsyn/xdc/synth.xdc

# Block Designs: bd/system_top_level/system_top_level.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_level || ORIG_REF_NAME==system_top_level} -quiet] -quiet

# IP: bd/system_top_level/ip/system_top_level_clk_wiz_0_1/system_top_level_clk_wiz_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_level_clk_wiz_0_1 || ORIG_REF_NAME==system_top_level_clk_wiz_0_1} -quiet] -quiet

# IP: bd/system_top_level/ip/system_top_level_util_vector_logic_0_0/system_top_level_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_level_util_vector_logic_0_0 || ORIG_REF_NAME==system_top_level_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/system_top_level/ip/system_top_level_i2c_config_0_0/system_top_level_i2c_config_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_level_i2c_config_0_0 || ORIG_REF_NAME==system_top_level_i2c_config_0_0} -quiet] -quiet

# IP: bd/system_top_level/ip/system_top_level_synthesizer_0_0/system_top_level_synthesizer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_level_synthesizer_0_0 || ORIG_REF_NAME==system_top_level_synthesizer_0_0} -quiet] -quiet

# XDC: d:/logsyn/syn/synth_top/synth_top.gen/sources_1/bd/system_top_level/ip/system_top_level_clk_wiz_0_1/system_top_level_clk_wiz_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_top_level_clk_wiz_0_1 || ORIG_REF_NAME==system_top_level_clk_wiz_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/logsyn/syn/synth_top/synth_top.gen/sources_1/bd/system_top_level/ip/system_top_level_clk_wiz_0_1/system_top_level_clk_wiz_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_top_level_clk_wiz_0_1 || ORIG_REF_NAME==system_top_level_clk_wiz_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/logsyn/syn/synth_top/synth_top.gen/sources_1/bd/system_top_level/ip/system_top_level_clk_wiz_0_1/system_top_level_clk_wiz_0_1_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_top_level_clk_wiz_0_1 || ORIG_REF_NAME==system_top_level_clk_wiz_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/logsyn/syn/synth_top/synth_top.gen/sources_1/bd/system_top_level/ip/system_top_level_clk_wiz_0_1/system_top_level_clk_wiz_0_1_ooc.xdc

# XDC: d:/logsyn/syn/synth_top/synth_top.gen/sources_1/bd/system_top_level/system_top_level_ooc.xdc
